sbatch batch_scripts/run_slurm_AG_small_infection.run 
sbatch batch_scripts/run_slurm_AG_small_death.run

sbatch batch_scripts/run_slurm_AG_small_death.run
sbatch batch_scripts/run_slurm_medium.run

sbatch batch_scripts/run_slurm_AG_medium_infection.run
batch batch_scripts/run_slurm_AG_medium_death.run

sbatch batch_scripts/run_slurm_big.run
